### ISSUE TITLE
net-ssh ruby 1.9

### ISSUE THREAD

**Issue by Rauldg** [rock-core/rock-package_set#83]
Hello,

I am using the rock15.05 tag here but I think this issue will happen also for users of the flavour stable as long as they use ruby1.9.

in https://github.com/rock-core/rock-package_set/blob/master/rock.osdeps#L123

net-ssh can't be updated because it requires ruby >= 2.0. 

This can be solved with:
```
net-ssh:                                                                                                                                  
    gem: "net-ssh<2.10"  
```

To which branch should this be pushed? I didn't find specific ruby19 os-dep files for this package, maybe this should go somewhere else?

@doudou 
@goldhoorn

**Comment by goldhoorn** [comment]
I set this to wont fix because i do not want to create another 15.05.2 release
Furthermore i will create soon a 15.10 release. This release will then require ruby2.0 which is available on all systems.
If someone can provide a tested solution i'm open to reopen this. Otherwise i close this now. Even this mean that rock15.05 is not fully working anymore. We will ever have such kind of problems with osdeps and i'm have not sufficent recousrces to keep all releases running.

**Comment by Rauldg** [comment]
OK.
This indeed fixes the for ruby1.9 (tested in my local installation) but is not ideal for posterior versions of Ruby. Therefore it should not go in the next release or stable flavour.

**Comment by doudou** [comment]
@goldhoorn: you say

> I set this to wont fix because i do not want to create another 15.05.2 release

Is that really that much work ? Does it involve more than checking out stable and running the release scripts ?

Anyways, we should patch the osdeps files to install ruby-net-ssh instead of the gem

@Rauldg: just create a blablabl.osdeps-ruby19 to add 1.9-specific changes

**Comment by goldhoorn** [comment]
On 30.09.2015 13:55, Sylvain Joyeux wrote:
>
> @goldhoorn <https://github.com/goldhoorn>: you say
>
>     I set this to wont fix because i do not want to create another
>     15.05.2 release
>
> Is that really that much work ? Does it involve more than checking out 
> stable and running the release scripts ?
>
Is is possible but not solve the general problem that the release might 
break because os osdep changes. Furthermore we will a new release soon 
ad this was the last one which support ruby1.9. AND the old release can 
be used with ruby2.0 which is available on all Systems we support.

> Anyways, we should patch the osdeps files to install ruby-net-ssh 
> instead of the gem
>
> @Rauldg <https://github.com/Rauldg>: just create a 
> blablabl.osdeps-ruby19 to add 1.9-specific changes
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/rock-package_set/issues/83#issuecomment-144374037>.
>


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
@Rauldg: I can't find any package that use net-ssh .... what depends on it ?

**Comment by doudou** [comment]
I reopen ... will try to do a tiny 15.05.2 to fix those

**Comment by Rauldg** [comment]
It is required for `drivers/orogen/monster_interface` this one is on the DFKI server.
I created a rock.osdeps-ruby19 and made a pull request on the branch rock-rc. Should it go to that branch?
https://github.com/rock-core/rock-package_set/pull/85

**Comment by goldhoorn** [comment]
The monster_itnerface is a dfki internal package.

I could not find any official rock package which depends on this, i
f this really the only package which depends on this i vote to remove 
the definition from this pacakge set in general.



On 01.10.2015 11:57, Raúl Domínguez wrote:
>
> It is required for |drivers/orogen/monster_interface| this one is on 
> the DFKI server.
> I created a rock.osdeps-ruby19 and made a pull request on the branch 
> rock-rc. Should it go to that branch?
> #85 <https://github.com/rock-core/rock-package_set/pull/85>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/rock-package_set/issues/83#issuecomment-144682931>.
>


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by Rauldg** [comment]
According to git-blame @jakobs included the net-ssh osdep. Maybe he knows if it is used by any DFKI external rock package.

**Comment by goldhoorn** [comment]
goldhoorn@mgoldhoorn:~/bootstraps/all/dev$ autoproj update 
--all-known-packages
goldhoorn@mgoldhoorn:~/bootstraps/all/dev$ find -name "manifest.xml" | 
xargs grep "net-ssh"
<nothing>

seems like it can be removed



On 01.10.2015 13:03, Raúl Domínguez wrote:
>
> According to git-blame @jakobs <https://github.com/jakobs> included 
> the net-ssh osdep. Maybe he knows if it is used by any DFKI external 
> rock package.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/rock-package_set/issues/83#issuecomment-144697858>.
>


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
> seems like it can be removed

We can't really do that, unfortunately, at least not on the release since some people might depend on it.
